{
  pkgs,
  rust-bin-custom,
  sce,
}:
pkgs.mkShell {
  name = "procurator";
  buildInputs = [
    pkgs.cargo-watch
    pkgs.pkg-config
    rust-bin-custom
    pkgs.capnproto
    # Used to run tests with the artifacts generated by the flakes
    pkgs.cloud-hypervisor
    # Used to try to genereate the openapi spec
    pkgs.openapi-generator-cli
    sce
  ];

  shellHook = ''
    export CARGO_MANIFEST_DIR="$PWD"
  '';
}
